import cantools
from CanDecoder import CanDecoder
from CanID_autogenerated import *


dbcPath = '../miscellaneous.can-ids/SBT.dbc'

canDecoder = CanDecoder(dbcPath)
frame = canDecoder.decode_mess(0xc0040, bytearray(b'\xc8y\t\x00\x00\x00\x00\x00'))

print(canDecoder.get_sourceID())

sourceIDname = sourceIDtoName[canDecoder.get_sourceID()]
paramIDname = paramIDtoName[canDecoder.get_paramID()]


for signal in frame:
    print("{}/{}/{} = {}".format(sourceIDname, paramIDname, signal, frame[signal]))
