import argparse
import can
from can.interface import Bus
import cantools
from CanDecoder import CanDecoder
from CanID_autogenerated import *
import time
from mqtt import MQTT

can_socket = "vcan0"
dbc_file = "../miscellaneous.can-ids/SBT.dbc"
mqtt_server = "pwraerospace.edu.pl"

# Init can socket
can.rc['interface'] = 'socketcan'
can.rc['channel'] = can_socket
can.rc['bitrate'] = 250000
bus = Bus()


# config can decoder
canDecoder = CanDecoder(dbc_file)

# The callback for when a PUBLISH message is received from the server.
def callback(topic, payload):
    keys = topic.split("/")
    extID = canDecoder.get_arbitrationID(keys[0], keys[1])    

    print(hex(extID))

# config MQTT
myMQTT = MQTT(mqtt_server, 1883)
myMQTT.subscribe("#", callback)
myMQTT.initConnection()

print("GO!")

while 1:
    # bus.send( can.Message(arbitration_id=0xC0FFEE, data=[1, 2, 3, 4, 5, 6, 7, 8], is_extended_id=True ))
    time.sleep(1)
    pass







