from CanDecoder import CanDecoder
from CanID_autogenerated import *
from mqtt import MQTT
from CanMQTT import canDecoder

# The callback for when a PUBLISH message is received from the server.


def callback(topic, threadValue):
    try:
        keys = topic.split("/")

        extID = canDecoder.encode_arbitrationID(
            keys[len(keys) - 3], keys[len(keys) - 2])

        canPayload = canDecoder.encode_payload(
            keys[len(keys) - 2], keys[len(keys) - 1], threadValue)

        print("New message from MQTT!")
        print("Sending to CAN: {} = {}".format(topic, threadValue))
        print()
        bus.send(can.Message(arbitration_id=extID,
                             data=canPayload, is_extended_id=True))
    except Exception as e:
        print("Error processing message: {}={}".format(topic, threadValue))
        print("Error: {}".format(e))
        print()
